---
title: "Ec 980FF Data Analysis"
author: "Buddy Scott"
date: "10/14/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggplot2)
```

```{r}

# Reading in the data
nbainfo <- read_csv("nbainfo.csv", 
                    col_type = cols(team = col_character(), 
                                    "1920winpct" = col_number(), 
                                    winpctrank = col_number(), 
                                    "1920ortg" = col_number(),
                                    ortgrank = col_number(), 
                                    "1920drtg" = col_number(), 
                                     drtgrank = col_number(), 
                                    "1920nrtg" = col_number(), 
                                     nrtgrank = col_number(), 
                                    "1920pace" = col_number(), 
                                     pacerank = col_number(), 
                                    gtcontracts = col_number(), 
                                    po_ngs = col_number(), 
                                    avgage = col_number(), 
                                    medage = col_number(), 
                                    avgexp = col_number(), 
                                    medexp = col_number(), 
                                    "2021projsalary" = col_number(), 
                                    "2021projcapspace" = col_number(), 
                                    "2021projexceptions" = col_character(), 
                                    tenyrwin = col_number(), 
                                    tenyrloss = col_number(), 
                                    tenyrwinpct = col_number(), 
                                    winpctrank_10 = col_number(), 
                                    playoffpct = col_number(), 
                                    principal_owner = col_character(), 
                                    nw = col_number(), 
                                    owned_since = col_number(), 
                                    business = col_character(), 
                                    other_owners = col_character(), 
                                    valuation = col_number(), 
                                    percent_change = col_number(), 
                                    debt_to_value = col_number(), 
                                    revenue = col_number(), 
                                    operating_income = col_number())) %>%
  rename_with(~ str_replace(.x, "1920", "current")) %>% 
  rename_with(~ str_replace(.x, "2021", "future")) %>% 
  slice(1:30)
```

```{r}

# Some cool graphs
nbainfo %>%
ggplot(aes(x = currentwinpct, y = valuation)) + 
  geom_point() + 
  stat_smooth(formula = y ~ x, method = "lm", se = TRUE)

nbainfo %>%
ggplot(aes(x = tenyrwinpct, y = valuation)) + 
  geom_point() + 
  stat_smooth(formula = y ~ x, method = "lm", se = TRUE)

nbainfo %>%
  ggplot(aes(x = fct_reorder(team, valuation), y = valuation)) + 
    geom_col() + 
    coord_flip() + 
    labs(title = "Team Valuations", x = "February 2020 Valuation", 
         y = "Team") + 
    scale_y_continuous(breaks = c(0, 1, 2, 3, 4),
                     labels = c("$0", "$1B", "$2B", "$3B", "$4B"))

nbainfo %>%
  ggplot(aes(x = fct_reorder(team, nw), y = nw)) + 
    geom_col() + 
    coord_flip() + 
    labs(title = "Team Majority Owner's Net Worth", x = "Net Worth", 
         y = "Team") + 
    scale_y_continuous(breaks = c(0, 20, 40, 60, 80),
                     labels = c("$0", "$20B", "$40B", "$60B", "$80B"))
  


```

